Rspec 3.5 compatibility
Previously Airborne.base was loaded before the configuration was added.
This caused an error:

```
Gem Load Error is: undefined method `requester_module' for
```

Waiting to load Airborne.base until the configuration has been added (`
config.add_setting :requester_module`) fixes the issue.

Fixes #121